### ISSUE TITLE
スポンサーを探す

### ISSUE THREAD

**Issue by kdmsnr** [coderdojo-suginami/coderdojo-suginami.github.io#7]
当面はワイクルさんが負担するかな。。。
会場はヴァルさんで。ヴァルさんの負担が大きいようなら別会場も探す。

**Comment by araratakeshi** [comment]
月1開催だと結構厳しいかな。
他の勉強会開催でも、土日に会社まで来たがる社員が基本的にほとんどいないです。
なので、VAL側では私ひとりになり単一障害点にになりやすいです。
1.5か月に1回の開催であれば、私ひとりで、まぁ大丈夫ですよ。

**Comment by araratakeshi** [comment]
ご利用可能な機材(オープンカフェ側 30人前後)
Wi-Fi、電源、プロジェクタ、黒板またはホワイトボード、マイク・スピーカー、Mac用アダプタ（Mini DisplayPort - VGA or HDMI アダプタ）
https://www.doorkeeper.jp/会場/vallaboratory

**Comment by araratakeshi** [comment]
もしかしたら、スポンサー費用として1回あたり数千円くらいの雑費（お菓子・ソフトドリンク）ならなんとかなるかもしれないです。
稟議とまではいかないですが、ちょっくら相談します。
弊社には子供向け商材がないから、宣伝的な何か理由付けが必要です。

**Comment by kdmsnr** [comment]
新井さんに負担をかけるのは申し訳ないので、会場はもうひとつ用意したほうがよいかもですねえ

moved to #8

**Comment by araratakeshi** [comment]
スポンサー費用として1回あたり数千円くらいの雑費（ドリンクやお菓子）の支出は私（部長権限）で大丈夫です。駅すぱあとのステッカーや付箋紙を宣伝材料のために配布させてください。

**Comment by kdmsnr** [comment]
ありがとうございます！
ステッカーも了解です。
